### ISSUE TITLE
Problème à l'installation.

### ISSUE THREAD

**Issue by domble42** [alexisju/albinomouse-template#3]
Bonjour,
J'utilise Shaarli 0.0.41 beta et j'éprouve quelques difficulté à mettre en place le thème.
- La modification de $GLOBALS['config']['RAINTPL_TPL'] = 'tpl/albinomouse-template/'; ne semble avoir aucun effet.
- Écraser les fichiers du dossier TPL par ceux de l'archive fonctionne (même si ce n'est pas idéal je trouve) mais fait sauter la date dans le listing des links.

**Comment by x4n4** [comment]
Ok, en fait il y a eu une reprise de Shaarli par la communauté, sauf que lorsqu'on tape shaarli dans un moteur de recherche, on arrive sur le dokuwiki de sebsauvage dont le lien download renvoie vers l'ancienne version.

**Comment by alexisju** [comment]
En effet, c'est regrettable que Sebsauvage ne mentionne pas l'existence de la version communautaire de Shaarli sur son wiki ou son Github, alors que cette version corrige pourtant des bugs et apporte des améliorations qu'il avait lui-même pointées, et qu'il ne développe plus Shaarli depuis plusieurs années. Il a déjà été sollicité plus d'une fois à ce sujet...
