### ISSUE TITLE
Add news link on mobile 

### ISSUE THREAD

**Issue by effemmeffe** [alexisju/albinomouse-template#7]
I can't find the add link button in mobile browser.

**Comment by alexisju** [comment]
You will find it under `Menu` button.

**Comment by effemmeffe** [comment]
No, I don't: http://imgur.com/3lp7hG9

**Comment by effemmeffe** [comment]
Sorry, wrong link, can't edit from mobile. 
The right link is: http://imgur.com/3lp7hG9

**Comment by alexisju** [comment]
You have to use [am_menu plugin](https://github.com/alexisju/am_menu) with Albinomouse template or customise your own menu file to have a functional menu with desired functions. Sorry if it was not clear.

**Comment by effemmeffe** [comment]
Thanks, now it works.
I'd write in the documentation that am_menu is mandatory, not just hughly recommended.

**Comment by alexisju** [comment]
I was thinking the mention was clear enough : _"I highly recommend you to use this template at least with "am_menu" plugin. AM Menu (AlbinoMouse menu) add you a default menu that you can also adapt to fit to your needs."_ 

By the way, there is others ways to add links, like bookmaklets or Firefox API.
